# Generated by Django 5.2.5 on 2025-09-06 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Изображение (URL)'),
        ),
        migrations.AddField(
            model_name='news_post',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='news_post',
            name='is_from_internet',
            field=models.BooleanField(default=False, verbose_name='Загружено из интернета'),
        ),
        migrations.AddField(
            model_name='news_post',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL источника'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='Краткое описание новости'),
        ),
        migrations.AlterField(
            model_name='news_post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название новости'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news_post', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('user', 'news_post')},
            },
        ),
        migrations.AddField(
            model_name='news_post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='news.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PendingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('source_url', models.URLField(verbose_name='URL источника')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем')),
            ],
            options={
                'verbose_name': 'Новость на модерации',
                'verbose_name_plural': 'Новости на модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
